name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: ['8.0', 8.1, 8.2, 8.3]
        laravel: [9.*, 10.*, 11.*]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: 9.*
            php: 8.1
          - laravel: 9.*
            php: 8.2
          - laravel: 9.*
            php: 8.3
          - laravel: 10.*
            php: '8.0'
          - laravel: 11.*
            php: '8.0'
          - laravel: 11.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/console:${{ matrix.laravel }}" "illuminate/mail:${{ matrix.laravel }}" "illuminate/view:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress
      - name: Execute tests
        run: vendor/bin/pest
